/* GENERATED by scripts/gen_ops_diff.py: reference for ops_isize.mvs */
#include <stdio.h>
#include <stdint.h>

int main(void) {
    {
        intptr_t a = (intptr_t)9223372036854775807LL; intptr_t b = (intptr_t)1LL;
        { intptr_t r = a + b; printf("%lld\n", (long long) r); }
        { intptr_t r = a - b; printf("%lld\n", (long long) r); }
        { intptr_t r = a * b; printf("%lld\n", (long long) r); }
        { intptr_t r = a & b; printf("%lld\n", (long long) r); }
        { intptr_t r = a | b; printf("%lld\n", (long long) r); }
        { intptr_t r = a ^ b; printf("%lld\n", (long long) r); }
        { intptr_t r = a / b; printf("%lld\n", (long long) r); }
        { intptr_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { intptr_t r = (intptr_t)(a << 1); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 1); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a << 3); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 3); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a << 63); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 63); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(~a); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        intptr_t a = (intptr_t)(-9223372036854775807LL - 1); intptr_t b = (intptr_t)1LL;
        { intptr_t r = a + b; printf("%lld\n", (long long) r); }
        { intptr_t r = a - b; printf("%lld\n", (long long) r); }
        { intptr_t r = a * b; printf("%lld\n", (long long) r); }
        { intptr_t r = a & b; printf("%lld\n", (long long) r); }
        { intptr_t r = a | b; printf("%lld\n", (long long) r); }
        { intptr_t r = a ^ b; printf("%lld\n", (long long) r); }
        { intptr_t r = a / b; printf("%lld\n", (long long) r); }
        { intptr_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { intptr_t r = (intptr_t)(~a); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        intptr_t a = (intptr_t)9223372036854775807LL; intptr_t b = (intptr_t)3LL;
        { intptr_t r = a + b; printf("%lld\n", (long long) r); }
        { intptr_t r = a - b; printf("%lld\n", (long long) r); }
        { intptr_t r = a * b; printf("%lld\n", (long long) r); }
        { intptr_t r = a & b; printf("%lld\n", (long long) r); }
        { intptr_t r = a | b; printf("%lld\n", (long long) r); }
        { intptr_t r = a ^ b; printf("%lld\n", (long long) r); }
        { intptr_t r = a / b; printf("%lld\n", (long long) r); }
        { intptr_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { intptr_t r = (intptr_t)(a << 1); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 1); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a << 3); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 3); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a << 63); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 63); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(~a); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        intptr_t a = (intptr_t)(-9223372036854775807LL - 1); intptr_t b = (intptr_t)7LL;
        { intptr_t r = a + b; printf("%lld\n", (long long) r); }
        { intptr_t r = a - b; printf("%lld\n", (long long) r); }
        { intptr_t r = a * b; printf("%lld\n", (long long) r); }
        { intptr_t r = a & b; printf("%lld\n", (long long) r); }
        { intptr_t r = a | b; printf("%lld\n", (long long) r); }
        { intptr_t r = a ^ b; printf("%lld\n", (long long) r); }
        { intptr_t r = a / b; printf("%lld\n", (long long) r); }
        { intptr_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { intptr_t r = (intptr_t)(~a); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        intptr_t a = (intptr_t)0LL; intptr_t b = (intptr_t)5LL;
        { intptr_t r = a + b; printf("%lld\n", (long long) r); }
        { intptr_t r = a - b; printf("%lld\n", (long long) r); }
        { intptr_t r = a * b; printf("%lld\n", (long long) r); }
        { intptr_t r = a & b; printf("%lld\n", (long long) r); }
        { intptr_t r = a | b; printf("%lld\n", (long long) r); }
        { intptr_t r = a ^ b; printf("%lld\n", (long long) r); }
        { intptr_t r = a / b; printf("%lld\n", (long long) r); }
        { intptr_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { intptr_t r = (intptr_t)(a << 1); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 1); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a << 3); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 3); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a << 63); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 63); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(~a); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        intptr_t a = (intptr_t)-1LL; intptr_t b = (intptr_t)-1LL;
        { intptr_t r = a + b; printf("%lld\n", (long long) r); }
        { intptr_t r = a - b; printf("%lld\n", (long long) r); }
        { intptr_t r = a * b; printf("%lld\n", (long long) r); }
        { intptr_t r = a & b; printf("%lld\n", (long long) r); }
        { intptr_t r = a | b; printf("%lld\n", (long long) r); }
        { intptr_t r = a ^ b; printf("%lld\n", (long long) r); }
        { intptr_t r = a / b; printf("%lld\n", (long long) r); }
        { intptr_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { intptr_t r = (intptr_t)(~a); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        intptr_t a = (intptr_t)7LL; intptr_t b = (intptr_t)3LL;
        { intptr_t r = a + b; printf("%lld\n", (long long) r); }
        { intptr_t r = a - b; printf("%lld\n", (long long) r); }
        { intptr_t r = a * b; printf("%lld\n", (long long) r); }
        { intptr_t r = a & b; printf("%lld\n", (long long) r); }
        { intptr_t r = a | b; printf("%lld\n", (long long) r); }
        { intptr_t r = a ^ b; printf("%lld\n", (long long) r); }
        { intptr_t r = a / b; printf("%lld\n", (long long) r); }
        { intptr_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { intptr_t r = (intptr_t)(a << 1); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 1); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a << 3); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 3); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a << 63); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 63); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(~a); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        intptr_t a = (intptr_t)-7LL; intptr_t b = (intptr_t)3LL;
        { intptr_t r = a + b; printf("%lld\n", (long long) r); }
        { intptr_t r = a - b; printf("%lld\n", (long long) r); }
        { intptr_t r = a * b; printf("%lld\n", (long long) r); }
        { intptr_t r = a & b; printf("%lld\n", (long long) r); }
        { intptr_t r = a | b; printf("%lld\n", (long long) r); }
        { intptr_t r = a ^ b; printf("%lld\n", (long long) r); }
        { intptr_t r = a / b; printf("%lld\n", (long long) r); }
        { intptr_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { intptr_t r = (intptr_t)(~a); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        intptr_t a = (intptr_t)7LL; intptr_t b = (intptr_t)-3LL;
        { intptr_t r = a + b; printf("%lld\n", (long long) r); }
        { intptr_t r = a - b; printf("%lld\n", (long long) r); }
        { intptr_t r = a * b; printf("%lld\n", (long long) r); }
        { intptr_t r = a & b; printf("%lld\n", (long long) r); }
        { intptr_t r = a | b; printf("%lld\n", (long long) r); }
        { intptr_t r = a ^ b; printf("%lld\n", (long long) r); }
        { intptr_t r = a / b; printf("%lld\n", (long long) r); }
        { intptr_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { intptr_t r = (intptr_t)(a << 1); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 1); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a << 3); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 3); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a << 63); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 63); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(~a); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        intptr_t a = (intptr_t)-7LL; intptr_t b = (intptr_t)-3LL;
        { intptr_t r = a + b; printf("%lld\n", (long long) r); }
        { intptr_t r = a - b; printf("%lld\n", (long long) r); }
        { intptr_t r = a * b; printf("%lld\n", (long long) r); }
        { intptr_t r = a & b; printf("%lld\n", (long long) r); }
        { intptr_t r = a | b; printf("%lld\n", (long long) r); }
        { intptr_t r = a ^ b; printf("%lld\n", (long long) r); }
        { intptr_t r = a / b; printf("%lld\n", (long long) r); }
        { intptr_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { intptr_t r = (intptr_t)(~a); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        intptr_t a = (intptr_t)4611686018427387906LL; intptr_t b = (intptr_t)9LL;
        { intptr_t r = a + b; printf("%lld\n", (long long) r); }
        { intptr_t r = a - b; printf("%lld\n", (long long) r); }
        { intptr_t r = a * b; printf("%lld\n", (long long) r); }
        { intptr_t r = a & b; printf("%lld\n", (long long) r); }
        { intptr_t r = a | b; printf("%lld\n", (long long) r); }
        { intptr_t r = a ^ b; printf("%lld\n", (long long) r); }
        { intptr_t r = a / b; printf("%lld\n", (long long) r); }
        { intptr_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { intptr_t r = (intptr_t)(a << 1); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 1); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a << 3); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 3); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a << 63); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(a >> 63); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(~a); printf("%lld\n", (long long) r); }
        { intptr_t r = (intptr_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    return 0;
}
