/* GENERATED by scripts/gen_ops_diff.py: reference for ops_u64.mvs */
#include <stdio.h>
#include <stdint.h>

int main(void) {
    {
        uint64_t a = (uint64_t)18446744073709551615ULL; uint64_t b = (uint64_t)1LL;
        { uint64_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint64_t r = (uint64_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a << 63); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 63); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint64_t a = (uint64_t)0LL; uint64_t b = (uint64_t)5LL;
        { uint64_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint64_t r = (uint64_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a << 63); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 63); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint64_t a = (uint64_t)18446744073709551615ULL; uint64_t b = (uint64_t)3LL;
        { uint64_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint64_t r = (uint64_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a << 63); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 63); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint64_t a = (uint64_t)9223372036854775810ULL; uint64_t b = (uint64_t)9LL;
        { uint64_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint64_t r = (uint64_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a << 63); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 63); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint64_t a = (uint64_t)7LL; uint64_t b = (uint64_t)3LL;
        { uint64_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint64_t r = (uint64_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a << 63); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 63); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint64_t a = (uint64_t)200LL; uint64_t b = (uint64_t)7LL;
        { uint64_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint64_t r = (uint64_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a << 63); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(a >> 63); printf("%llu\n", (unsigned long long) r); }
        { uint64_t r = (uint64_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    return 0;
}
