/* GENERATED by scripts/gen_ops_diff.py: reference for ops_f64.mvs */
#include <stdio.h>

int main(void) {
    {
        double a = 1.0; double b = 3.0;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0 - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(double)(long long)a);
    }
    {
        double a = 2.5; double b = 0.5;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0 - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(double)(long long)a);
    }
    {
        double a = -7.25; double b = 2.0;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0 - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(double)(long long)a);
    }
    {
        double a = 0.0; double b = 5.0;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0 - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(double)(long long)a);
    }
    {
        double a = 1e+18; double b = 3.0;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0 - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(double)(long long)a);
    }
    {
        double a = 0.1; double b = 0.2;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0 - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(double)(long long)a);
    }
    {
        double a = -0.5; double b = -0.25;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0 - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(double)(long long)a);
    }
    {
        double a = 123456.789; double b = 1000.0;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0 - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(double)(long long)a);
    }
    {
        double a = 1e-07; double b = 3.0;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0 - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(double)(long long)a);
    }
    return 0;
}
