/* GENERATED by scripts/gen_ops_diff.py: reference for ops_f32.mvs */
#include <stdio.h>

int main(void) {
    {
        float a = 1.0f; float b = 3.0f;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0f - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(float)(long long)a);
    }
    {
        float a = 2.5f; float b = 0.5f;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0f - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(float)(long long)a);
    }
    {
        float a = -7.25f; float b = 2.0f;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0f - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(float)(long long)a);
    }
    {
        float a = 0.0f; float b = 5.0f;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0f - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(float)(long long)a);
    }
    {
        float a = 1e+18f; float b = 3.0f;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0f - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(float)(long long)a);
    }
    {
        float a = 0.1f; float b = 0.2f;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0f - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(float)(long long)a);
    }
    {
        float a = -0.5f; float b = -0.25f;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0f - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(float)(long long)a);
    }
    {
        float a = 123456.789f; float b = 1000.0f;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0f - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(float)(long long)a);
    }
    {
        float a = 1e-07f; float b = 3.0f;
        printf("%f\n", (double)(a + b));
        printf("%f\n", (double)(a - b));
        printf("%f\n", (double)(a * b));
        printf("%f\n", (double)(a / b));
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        printf("%f\n", (double)(0.0f - a));
        printf("%lld\n", (long long)a);
        printf("%f\n", (double)(float)(long long)a);
    }
    return 0;
}
