/* GENERATED by scripts/gen_ops_diff.py: reference for ops_u16.mvs */
#include <stdio.h>
#include <stdint.h>

int main(void) {
    {
        uint16_t a = (uint16_t)65535LL; uint16_t b = (uint16_t)1LL;
        { uint16_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint16_t r = (uint16_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a << 15); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 15); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint16_t a = (uint16_t)0LL; uint16_t b = (uint16_t)5LL;
        { uint16_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint16_t r = (uint16_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a << 15); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 15); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint16_t a = (uint16_t)65535LL; uint16_t b = (uint16_t)3LL;
        { uint16_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint16_t r = (uint16_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a << 15); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 15); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint16_t a = (uint16_t)32770LL; uint16_t b = (uint16_t)9LL;
        { uint16_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint16_t r = (uint16_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a << 15); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 15); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint16_t a = (uint16_t)7LL; uint16_t b = (uint16_t)3LL;
        { uint16_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint16_t r = (uint16_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a << 15); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 15); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint16_t a = (uint16_t)200LL; uint16_t b = (uint16_t)7LL;
        { uint16_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint16_t r = (uint16_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a << 15); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(a >> 15); printf("%llu\n", (unsigned long long) r); }
        { uint16_t r = (uint16_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    return 0;
}
