/* GENERATED by scripts/gen_ops_diff.py: reference for ops_u8.mvs */
#include <stdio.h>
#include <stdint.h>

int main(void) {
    {
        uint8_t a = (uint8_t)255LL; uint8_t b = (uint8_t)1LL;
        { uint8_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint8_t r = (uint8_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a << 7); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 7); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint8_t a = (uint8_t)0LL; uint8_t b = (uint8_t)5LL;
        { uint8_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint8_t r = (uint8_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a << 7); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 7); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint8_t a = (uint8_t)255LL; uint8_t b = (uint8_t)3LL;
        { uint8_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint8_t r = (uint8_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a << 7); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 7); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint8_t a = (uint8_t)130LL; uint8_t b = (uint8_t)9LL;
        { uint8_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint8_t r = (uint8_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a << 7); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 7); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint8_t a = (uint8_t)7LL; uint8_t b = (uint8_t)3LL;
        { uint8_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint8_t r = (uint8_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a << 7); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 7); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint8_t a = (uint8_t)200LL; uint8_t b = (uint8_t)7LL;
        { uint8_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint8_t r = (uint8_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a << 7); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(a >> 7); printf("%llu\n", (unsigned long long) r); }
        { uint8_t r = (uint8_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    return 0;
}
