/* GENERATED by scripts/gen_ops_diff.py: reference for ops_i32.mvs */
#include <stdio.h>
#include <stdint.h>

int main(void) {
    {
        int32_t a = (int32_t)2147483647LL; int32_t b = (int32_t)1LL;
        { int32_t r = a + b; printf("%lld\n", (long long) r); }
        { int32_t r = a - b; printf("%lld\n", (long long) r); }
        { int32_t r = a * b; printf("%lld\n", (long long) r); }
        { int32_t r = a & b; printf("%lld\n", (long long) r); }
        { int32_t r = a | b; printf("%lld\n", (long long) r); }
        { int32_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int32_t r = a / b; printf("%lld\n", (long long) r); }
        { int32_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int32_t r = (int32_t)(a << 1); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a << 3); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a << 31); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 31); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(~a); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int32_t a = (int32_t)-2147483648LL; int32_t b = (int32_t)1LL;
        { int32_t r = a + b; printf("%lld\n", (long long) r); }
        { int32_t r = a - b; printf("%lld\n", (long long) r); }
        { int32_t r = a * b; printf("%lld\n", (long long) r); }
        { int32_t r = a & b; printf("%lld\n", (long long) r); }
        { int32_t r = a | b; printf("%lld\n", (long long) r); }
        { int32_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int32_t r = a / b; printf("%lld\n", (long long) r); }
        { int32_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int32_t r = (int32_t)(~a); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int32_t a = (int32_t)2147483647LL; int32_t b = (int32_t)3LL;
        { int32_t r = a + b; printf("%lld\n", (long long) r); }
        { int32_t r = a - b; printf("%lld\n", (long long) r); }
        { int32_t r = a * b; printf("%lld\n", (long long) r); }
        { int32_t r = a & b; printf("%lld\n", (long long) r); }
        { int32_t r = a | b; printf("%lld\n", (long long) r); }
        { int32_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int32_t r = a / b; printf("%lld\n", (long long) r); }
        { int32_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int32_t r = (int32_t)(a << 1); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a << 3); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a << 31); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 31); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(~a); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int32_t a = (int32_t)-2147483648LL; int32_t b = (int32_t)7LL;
        { int32_t r = a + b; printf("%lld\n", (long long) r); }
        { int32_t r = a - b; printf("%lld\n", (long long) r); }
        { int32_t r = a * b; printf("%lld\n", (long long) r); }
        { int32_t r = a & b; printf("%lld\n", (long long) r); }
        { int32_t r = a | b; printf("%lld\n", (long long) r); }
        { int32_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int32_t r = a / b; printf("%lld\n", (long long) r); }
        { int32_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int32_t r = (int32_t)(~a); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int32_t a = (int32_t)0LL; int32_t b = (int32_t)5LL;
        { int32_t r = a + b; printf("%lld\n", (long long) r); }
        { int32_t r = a - b; printf("%lld\n", (long long) r); }
        { int32_t r = a * b; printf("%lld\n", (long long) r); }
        { int32_t r = a & b; printf("%lld\n", (long long) r); }
        { int32_t r = a | b; printf("%lld\n", (long long) r); }
        { int32_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int32_t r = a / b; printf("%lld\n", (long long) r); }
        { int32_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int32_t r = (int32_t)(a << 1); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a << 3); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a << 31); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 31); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(~a); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int32_t a = (int32_t)-1LL; int32_t b = (int32_t)-1LL;
        { int32_t r = a + b; printf("%lld\n", (long long) r); }
        { int32_t r = a - b; printf("%lld\n", (long long) r); }
        { int32_t r = a * b; printf("%lld\n", (long long) r); }
        { int32_t r = a & b; printf("%lld\n", (long long) r); }
        { int32_t r = a | b; printf("%lld\n", (long long) r); }
        { int32_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int32_t r = a / b; printf("%lld\n", (long long) r); }
        { int32_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int32_t r = (int32_t)(~a); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int32_t a = (int32_t)7LL; int32_t b = (int32_t)3LL;
        { int32_t r = a + b; printf("%lld\n", (long long) r); }
        { int32_t r = a - b; printf("%lld\n", (long long) r); }
        { int32_t r = a * b; printf("%lld\n", (long long) r); }
        { int32_t r = a & b; printf("%lld\n", (long long) r); }
        { int32_t r = a | b; printf("%lld\n", (long long) r); }
        { int32_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int32_t r = a / b; printf("%lld\n", (long long) r); }
        { int32_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int32_t r = (int32_t)(a << 1); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a << 3); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a << 31); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 31); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(~a); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int32_t a = (int32_t)-7LL; int32_t b = (int32_t)3LL;
        { int32_t r = a + b; printf("%lld\n", (long long) r); }
        { int32_t r = a - b; printf("%lld\n", (long long) r); }
        { int32_t r = a * b; printf("%lld\n", (long long) r); }
        { int32_t r = a & b; printf("%lld\n", (long long) r); }
        { int32_t r = a | b; printf("%lld\n", (long long) r); }
        { int32_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int32_t r = a / b; printf("%lld\n", (long long) r); }
        { int32_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int32_t r = (int32_t)(~a); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int32_t a = (int32_t)7LL; int32_t b = (int32_t)-3LL;
        { int32_t r = a + b; printf("%lld\n", (long long) r); }
        { int32_t r = a - b; printf("%lld\n", (long long) r); }
        { int32_t r = a * b; printf("%lld\n", (long long) r); }
        { int32_t r = a & b; printf("%lld\n", (long long) r); }
        { int32_t r = a | b; printf("%lld\n", (long long) r); }
        { int32_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int32_t r = a / b; printf("%lld\n", (long long) r); }
        { int32_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int32_t r = (int32_t)(a << 1); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a << 3); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a << 31); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 31); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(~a); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int32_t a = (int32_t)-7LL; int32_t b = (int32_t)-3LL;
        { int32_t r = a + b; printf("%lld\n", (long long) r); }
        { int32_t r = a - b; printf("%lld\n", (long long) r); }
        { int32_t r = a * b; printf("%lld\n", (long long) r); }
        { int32_t r = a & b; printf("%lld\n", (long long) r); }
        { int32_t r = a | b; printf("%lld\n", (long long) r); }
        { int32_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int32_t r = a / b; printf("%lld\n", (long long) r); }
        { int32_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int32_t r = (int32_t)(~a); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int32_t a = (int32_t)1073741826LL; int32_t b = (int32_t)9LL;
        { int32_t r = a + b; printf("%lld\n", (long long) r); }
        { int32_t r = a - b; printf("%lld\n", (long long) r); }
        { int32_t r = a * b; printf("%lld\n", (long long) r); }
        { int32_t r = a & b; printf("%lld\n", (long long) r); }
        { int32_t r = a | b; printf("%lld\n", (long long) r); }
        { int32_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int32_t r = a / b; printf("%lld\n", (long long) r); }
        { int32_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int32_t r = (int32_t)(a << 1); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a << 3); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a << 31); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(a >> 31); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(~a); printf("%lld\n", (long long) r); }
        { int32_t r = (int32_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    return 0;
}
