/* GENERATED by scripts/gen_ops_diff.py: reference for ops_usize.mvs */
#include <stdio.h>
#include <stdint.h>

int main(void) {
    {
        uintptr_t a = (uintptr_t)18446744073709551615ULL; uintptr_t b = (uintptr_t)1LL;
        { uintptr_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uintptr_t r = (uintptr_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a << 63); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 63); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uintptr_t a = (uintptr_t)0LL; uintptr_t b = (uintptr_t)5LL;
        { uintptr_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uintptr_t r = (uintptr_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a << 63); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 63); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uintptr_t a = (uintptr_t)18446744073709551615ULL; uintptr_t b = (uintptr_t)3LL;
        { uintptr_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uintptr_t r = (uintptr_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a << 63); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 63); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uintptr_t a = (uintptr_t)9223372036854775810ULL; uintptr_t b = (uintptr_t)9LL;
        { uintptr_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uintptr_t r = (uintptr_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a << 63); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 63); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uintptr_t a = (uintptr_t)7LL; uintptr_t b = (uintptr_t)3LL;
        { uintptr_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uintptr_t r = (uintptr_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a << 63); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 63); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uintptr_t a = (uintptr_t)200LL; uintptr_t b = (uintptr_t)7LL;
        { uintptr_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uintptr_t r = (uintptr_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a << 63); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(a >> 63); printf("%llu\n", (unsigned long long) r); }
        { uintptr_t r = (uintptr_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    return 0;
}
