/* GENERATED by scripts/gen_ops_diff.py: reference for ops_i64.mvs */
#include <stdio.h>
#include <stdint.h>

int main(void) {
    {
        int64_t a = (int64_t)9223372036854775807LL; int64_t b = (int64_t)1LL;
        { int64_t r = a + b; printf("%lld\n", (long long) r); }
        { int64_t r = a - b; printf("%lld\n", (long long) r); }
        { int64_t r = a * b; printf("%lld\n", (long long) r); }
        { int64_t r = a & b; printf("%lld\n", (long long) r); }
        { int64_t r = a | b; printf("%lld\n", (long long) r); }
        { int64_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int64_t r = a / b; printf("%lld\n", (long long) r); }
        { int64_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int64_t r = (int64_t)(a << 1); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a << 3); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a << 63); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 63); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(~a); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int64_t a = (int64_t)(-9223372036854775807LL - 1); int64_t b = (int64_t)1LL;
        { int64_t r = a + b; printf("%lld\n", (long long) r); }
        { int64_t r = a - b; printf("%lld\n", (long long) r); }
        { int64_t r = a * b; printf("%lld\n", (long long) r); }
        { int64_t r = a & b; printf("%lld\n", (long long) r); }
        { int64_t r = a | b; printf("%lld\n", (long long) r); }
        { int64_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int64_t r = a / b; printf("%lld\n", (long long) r); }
        { int64_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int64_t r = (int64_t)(~a); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int64_t a = (int64_t)9223372036854775807LL; int64_t b = (int64_t)3LL;
        { int64_t r = a + b; printf("%lld\n", (long long) r); }
        { int64_t r = a - b; printf("%lld\n", (long long) r); }
        { int64_t r = a * b; printf("%lld\n", (long long) r); }
        { int64_t r = a & b; printf("%lld\n", (long long) r); }
        { int64_t r = a | b; printf("%lld\n", (long long) r); }
        { int64_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int64_t r = a / b; printf("%lld\n", (long long) r); }
        { int64_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int64_t r = (int64_t)(a << 1); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a << 3); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a << 63); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 63); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(~a); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int64_t a = (int64_t)(-9223372036854775807LL - 1); int64_t b = (int64_t)7LL;
        { int64_t r = a + b; printf("%lld\n", (long long) r); }
        { int64_t r = a - b; printf("%lld\n", (long long) r); }
        { int64_t r = a * b; printf("%lld\n", (long long) r); }
        { int64_t r = a & b; printf("%lld\n", (long long) r); }
        { int64_t r = a | b; printf("%lld\n", (long long) r); }
        { int64_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int64_t r = a / b; printf("%lld\n", (long long) r); }
        { int64_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int64_t r = (int64_t)(~a); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int64_t a = (int64_t)0LL; int64_t b = (int64_t)5LL;
        { int64_t r = a + b; printf("%lld\n", (long long) r); }
        { int64_t r = a - b; printf("%lld\n", (long long) r); }
        { int64_t r = a * b; printf("%lld\n", (long long) r); }
        { int64_t r = a & b; printf("%lld\n", (long long) r); }
        { int64_t r = a | b; printf("%lld\n", (long long) r); }
        { int64_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int64_t r = a / b; printf("%lld\n", (long long) r); }
        { int64_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int64_t r = (int64_t)(a << 1); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a << 3); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a << 63); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 63); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(~a); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int64_t a = (int64_t)-1LL; int64_t b = (int64_t)-1LL;
        { int64_t r = a + b; printf("%lld\n", (long long) r); }
        { int64_t r = a - b; printf("%lld\n", (long long) r); }
        { int64_t r = a * b; printf("%lld\n", (long long) r); }
        { int64_t r = a & b; printf("%lld\n", (long long) r); }
        { int64_t r = a | b; printf("%lld\n", (long long) r); }
        { int64_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int64_t r = a / b; printf("%lld\n", (long long) r); }
        { int64_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int64_t r = (int64_t)(~a); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int64_t a = (int64_t)7LL; int64_t b = (int64_t)3LL;
        { int64_t r = a + b; printf("%lld\n", (long long) r); }
        { int64_t r = a - b; printf("%lld\n", (long long) r); }
        { int64_t r = a * b; printf("%lld\n", (long long) r); }
        { int64_t r = a & b; printf("%lld\n", (long long) r); }
        { int64_t r = a | b; printf("%lld\n", (long long) r); }
        { int64_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int64_t r = a / b; printf("%lld\n", (long long) r); }
        { int64_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int64_t r = (int64_t)(a << 1); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a << 3); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a << 63); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 63); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(~a); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int64_t a = (int64_t)-7LL; int64_t b = (int64_t)3LL;
        { int64_t r = a + b; printf("%lld\n", (long long) r); }
        { int64_t r = a - b; printf("%lld\n", (long long) r); }
        { int64_t r = a * b; printf("%lld\n", (long long) r); }
        { int64_t r = a & b; printf("%lld\n", (long long) r); }
        { int64_t r = a | b; printf("%lld\n", (long long) r); }
        { int64_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int64_t r = a / b; printf("%lld\n", (long long) r); }
        { int64_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int64_t r = (int64_t)(~a); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int64_t a = (int64_t)7LL; int64_t b = (int64_t)-3LL;
        { int64_t r = a + b; printf("%lld\n", (long long) r); }
        { int64_t r = a - b; printf("%lld\n", (long long) r); }
        { int64_t r = a * b; printf("%lld\n", (long long) r); }
        { int64_t r = a & b; printf("%lld\n", (long long) r); }
        { int64_t r = a | b; printf("%lld\n", (long long) r); }
        { int64_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int64_t r = a / b; printf("%lld\n", (long long) r); }
        { int64_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int64_t r = (int64_t)(a << 1); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a << 3); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a << 63); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 63); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(~a); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int64_t a = (int64_t)-7LL; int64_t b = (int64_t)-3LL;
        { int64_t r = a + b; printf("%lld\n", (long long) r); }
        { int64_t r = a - b; printf("%lld\n", (long long) r); }
        { int64_t r = a * b; printf("%lld\n", (long long) r); }
        { int64_t r = a & b; printf("%lld\n", (long long) r); }
        { int64_t r = a | b; printf("%lld\n", (long long) r); }
        { int64_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int64_t r = a / b; printf("%lld\n", (long long) r); }
        { int64_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int64_t r = (int64_t)(~a); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int64_t a = (int64_t)4611686018427387906LL; int64_t b = (int64_t)9LL;
        { int64_t r = a + b; printf("%lld\n", (long long) r); }
        { int64_t r = a - b; printf("%lld\n", (long long) r); }
        { int64_t r = a * b; printf("%lld\n", (long long) r); }
        { int64_t r = a & b; printf("%lld\n", (long long) r); }
        { int64_t r = a | b; printf("%lld\n", (long long) r); }
        { int64_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int64_t r = a / b; printf("%lld\n", (long long) r); }
        { int64_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int64_t r = (int64_t)(a << 1); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a << 3); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a << 63); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(a >> 63); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(~a); printf("%lld\n", (long long) r); }
        { int64_t r = (int64_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    return 0;
}
