/* GENERATED by scripts/gen_ops_diff.py: reference for ops_i8.mvs */
#include <stdio.h>
#include <stdint.h>

int main(void) {
    {
        int8_t a = (int8_t)127LL; int8_t b = (int8_t)1LL;
        { int8_t r = a + b; printf("%lld\n", (long long) r); }
        { int8_t r = a - b; printf("%lld\n", (long long) r); }
        { int8_t r = a * b; printf("%lld\n", (long long) r); }
        { int8_t r = a & b; printf("%lld\n", (long long) r); }
        { int8_t r = a | b; printf("%lld\n", (long long) r); }
        { int8_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int8_t r = a / b; printf("%lld\n", (long long) r); }
        { int8_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int8_t r = (int8_t)(a << 1); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a << 3); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a << 7); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 7); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(~a); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int8_t a = (int8_t)-128LL; int8_t b = (int8_t)1LL;
        { int8_t r = a + b; printf("%lld\n", (long long) r); }
        { int8_t r = a - b; printf("%lld\n", (long long) r); }
        { int8_t r = a * b; printf("%lld\n", (long long) r); }
        { int8_t r = a & b; printf("%lld\n", (long long) r); }
        { int8_t r = a | b; printf("%lld\n", (long long) r); }
        { int8_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int8_t r = a / b; printf("%lld\n", (long long) r); }
        { int8_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int8_t r = (int8_t)(~a); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int8_t a = (int8_t)127LL; int8_t b = (int8_t)3LL;
        { int8_t r = a + b; printf("%lld\n", (long long) r); }
        { int8_t r = a - b; printf("%lld\n", (long long) r); }
        { int8_t r = a * b; printf("%lld\n", (long long) r); }
        { int8_t r = a & b; printf("%lld\n", (long long) r); }
        { int8_t r = a | b; printf("%lld\n", (long long) r); }
        { int8_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int8_t r = a / b; printf("%lld\n", (long long) r); }
        { int8_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int8_t r = (int8_t)(a << 1); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a << 3); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a << 7); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 7); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(~a); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int8_t a = (int8_t)-128LL; int8_t b = (int8_t)7LL;
        { int8_t r = a + b; printf("%lld\n", (long long) r); }
        { int8_t r = a - b; printf("%lld\n", (long long) r); }
        { int8_t r = a * b; printf("%lld\n", (long long) r); }
        { int8_t r = a & b; printf("%lld\n", (long long) r); }
        { int8_t r = a | b; printf("%lld\n", (long long) r); }
        { int8_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int8_t r = a / b; printf("%lld\n", (long long) r); }
        { int8_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int8_t r = (int8_t)(~a); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int8_t a = (int8_t)0LL; int8_t b = (int8_t)5LL;
        { int8_t r = a + b; printf("%lld\n", (long long) r); }
        { int8_t r = a - b; printf("%lld\n", (long long) r); }
        { int8_t r = a * b; printf("%lld\n", (long long) r); }
        { int8_t r = a & b; printf("%lld\n", (long long) r); }
        { int8_t r = a | b; printf("%lld\n", (long long) r); }
        { int8_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int8_t r = a / b; printf("%lld\n", (long long) r); }
        { int8_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int8_t r = (int8_t)(a << 1); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a << 3); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a << 7); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 7); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(~a); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int8_t a = (int8_t)-1LL; int8_t b = (int8_t)-1LL;
        { int8_t r = a + b; printf("%lld\n", (long long) r); }
        { int8_t r = a - b; printf("%lld\n", (long long) r); }
        { int8_t r = a * b; printf("%lld\n", (long long) r); }
        { int8_t r = a & b; printf("%lld\n", (long long) r); }
        { int8_t r = a | b; printf("%lld\n", (long long) r); }
        { int8_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int8_t r = a / b; printf("%lld\n", (long long) r); }
        { int8_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int8_t r = (int8_t)(~a); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int8_t a = (int8_t)7LL; int8_t b = (int8_t)3LL;
        { int8_t r = a + b; printf("%lld\n", (long long) r); }
        { int8_t r = a - b; printf("%lld\n", (long long) r); }
        { int8_t r = a * b; printf("%lld\n", (long long) r); }
        { int8_t r = a & b; printf("%lld\n", (long long) r); }
        { int8_t r = a | b; printf("%lld\n", (long long) r); }
        { int8_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int8_t r = a / b; printf("%lld\n", (long long) r); }
        { int8_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int8_t r = (int8_t)(a << 1); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a << 3); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a << 7); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 7); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(~a); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int8_t a = (int8_t)-7LL; int8_t b = (int8_t)3LL;
        { int8_t r = a + b; printf("%lld\n", (long long) r); }
        { int8_t r = a - b; printf("%lld\n", (long long) r); }
        { int8_t r = a * b; printf("%lld\n", (long long) r); }
        { int8_t r = a & b; printf("%lld\n", (long long) r); }
        { int8_t r = a | b; printf("%lld\n", (long long) r); }
        { int8_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int8_t r = a / b; printf("%lld\n", (long long) r); }
        { int8_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int8_t r = (int8_t)(~a); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int8_t a = (int8_t)7LL; int8_t b = (int8_t)-3LL;
        { int8_t r = a + b; printf("%lld\n", (long long) r); }
        { int8_t r = a - b; printf("%lld\n", (long long) r); }
        { int8_t r = a * b; printf("%lld\n", (long long) r); }
        { int8_t r = a & b; printf("%lld\n", (long long) r); }
        { int8_t r = a | b; printf("%lld\n", (long long) r); }
        { int8_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int8_t r = a / b; printf("%lld\n", (long long) r); }
        { int8_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int8_t r = (int8_t)(a << 1); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a << 3); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a << 7); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 7); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(~a); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int8_t a = (int8_t)-7LL; int8_t b = (int8_t)-3LL;
        { int8_t r = a + b; printf("%lld\n", (long long) r); }
        { int8_t r = a - b; printf("%lld\n", (long long) r); }
        { int8_t r = a * b; printf("%lld\n", (long long) r); }
        { int8_t r = a & b; printf("%lld\n", (long long) r); }
        { int8_t r = a | b; printf("%lld\n", (long long) r); }
        { int8_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int8_t r = a / b; printf("%lld\n", (long long) r); }
        { int8_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int8_t r = (int8_t)(~a); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int8_t a = (int8_t)66LL; int8_t b = (int8_t)9LL;
        { int8_t r = a + b; printf("%lld\n", (long long) r); }
        { int8_t r = a - b; printf("%lld\n", (long long) r); }
        { int8_t r = a * b; printf("%lld\n", (long long) r); }
        { int8_t r = a & b; printf("%lld\n", (long long) r); }
        { int8_t r = a | b; printf("%lld\n", (long long) r); }
        { int8_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int8_t r = a / b; printf("%lld\n", (long long) r); }
        { int8_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int8_t r = (int8_t)(a << 1); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a << 3); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a << 7); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(a >> 7); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(~a); printf("%lld\n", (long long) r); }
        { int8_t r = (int8_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    return 0;
}
