/* GENERATED by scripts/gen_ops_diff.py: reference for ops_i16.mvs */
#include <stdio.h>
#include <stdint.h>

int main(void) {
    {
        int16_t a = (int16_t)32767LL; int16_t b = (int16_t)1LL;
        { int16_t r = a + b; printf("%lld\n", (long long) r); }
        { int16_t r = a - b; printf("%lld\n", (long long) r); }
        { int16_t r = a * b; printf("%lld\n", (long long) r); }
        { int16_t r = a & b; printf("%lld\n", (long long) r); }
        { int16_t r = a | b; printf("%lld\n", (long long) r); }
        { int16_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int16_t r = a / b; printf("%lld\n", (long long) r); }
        { int16_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int16_t r = (int16_t)(a << 1); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a << 3); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a << 15); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 15); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(~a); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int16_t a = (int16_t)-32768LL; int16_t b = (int16_t)1LL;
        { int16_t r = a + b; printf("%lld\n", (long long) r); }
        { int16_t r = a - b; printf("%lld\n", (long long) r); }
        { int16_t r = a * b; printf("%lld\n", (long long) r); }
        { int16_t r = a & b; printf("%lld\n", (long long) r); }
        { int16_t r = a | b; printf("%lld\n", (long long) r); }
        { int16_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int16_t r = a / b; printf("%lld\n", (long long) r); }
        { int16_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int16_t r = (int16_t)(~a); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int16_t a = (int16_t)32767LL; int16_t b = (int16_t)3LL;
        { int16_t r = a + b; printf("%lld\n", (long long) r); }
        { int16_t r = a - b; printf("%lld\n", (long long) r); }
        { int16_t r = a * b; printf("%lld\n", (long long) r); }
        { int16_t r = a & b; printf("%lld\n", (long long) r); }
        { int16_t r = a | b; printf("%lld\n", (long long) r); }
        { int16_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int16_t r = a / b; printf("%lld\n", (long long) r); }
        { int16_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int16_t r = (int16_t)(a << 1); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a << 3); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a << 15); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 15); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(~a); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int16_t a = (int16_t)-32768LL; int16_t b = (int16_t)7LL;
        { int16_t r = a + b; printf("%lld\n", (long long) r); }
        { int16_t r = a - b; printf("%lld\n", (long long) r); }
        { int16_t r = a * b; printf("%lld\n", (long long) r); }
        { int16_t r = a & b; printf("%lld\n", (long long) r); }
        { int16_t r = a | b; printf("%lld\n", (long long) r); }
        { int16_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int16_t r = a / b; printf("%lld\n", (long long) r); }
        { int16_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int16_t r = (int16_t)(~a); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int16_t a = (int16_t)0LL; int16_t b = (int16_t)5LL;
        { int16_t r = a + b; printf("%lld\n", (long long) r); }
        { int16_t r = a - b; printf("%lld\n", (long long) r); }
        { int16_t r = a * b; printf("%lld\n", (long long) r); }
        { int16_t r = a & b; printf("%lld\n", (long long) r); }
        { int16_t r = a | b; printf("%lld\n", (long long) r); }
        { int16_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int16_t r = a / b; printf("%lld\n", (long long) r); }
        { int16_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int16_t r = (int16_t)(a << 1); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a << 3); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a << 15); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 15); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(~a); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int16_t a = (int16_t)-1LL; int16_t b = (int16_t)-1LL;
        { int16_t r = a + b; printf("%lld\n", (long long) r); }
        { int16_t r = a - b; printf("%lld\n", (long long) r); }
        { int16_t r = a * b; printf("%lld\n", (long long) r); }
        { int16_t r = a & b; printf("%lld\n", (long long) r); }
        { int16_t r = a | b; printf("%lld\n", (long long) r); }
        { int16_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int16_t r = a / b; printf("%lld\n", (long long) r); }
        { int16_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int16_t r = (int16_t)(~a); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int16_t a = (int16_t)7LL; int16_t b = (int16_t)3LL;
        { int16_t r = a + b; printf("%lld\n", (long long) r); }
        { int16_t r = a - b; printf("%lld\n", (long long) r); }
        { int16_t r = a * b; printf("%lld\n", (long long) r); }
        { int16_t r = a & b; printf("%lld\n", (long long) r); }
        { int16_t r = a | b; printf("%lld\n", (long long) r); }
        { int16_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int16_t r = a / b; printf("%lld\n", (long long) r); }
        { int16_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int16_t r = (int16_t)(a << 1); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a << 3); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a << 15); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 15); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(~a); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int16_t a = (int16_t)-7LL; int16_t b = (int16_t)3LL;
        { int16_t r = a + b; printf("%lld\n", (long long) r); }
        { int16_t r = a - b; printf("%lld\n", (long long) r); }
        { int16_t r = a * b; printf("%lld\n", (long long) r); }
        { int16_t r = a & b; printf("%lld\n", (long long) r); }
        { int16_t r = a | b; printf("%lld\n", (long long) r); }
        { int16_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int16_t r = a / b; printf("%lld\n", (long long) r); }
        { int16_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int16_t r = (int16_t)(~a); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int16_t a = (int16_t)7LL; int16_t b = (int16_t)-3LL;
        { int16_t r = a + b; printf("%lld\n", (long long) r); }
        { int16_t r = a - b; printf("%lld\n", (long long) r); }
        { int16_t r = a * b; printf("%lld\n", (long long) r); }
        { int16_t r = a & b; printf("%lld\n", (long long) r); }
        { int16_t r = a | b; printf("%lld\n", (long long) r); }
        { int16_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int16_t r = a / b; printf("%lld\n", (long long) r); }
        { int16_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int16_t r = (int16_t)(a << 1); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a << 3); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a << 15); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 15); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(~a); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int16_t a = (int16_t)-7LL; int16_t b = (int16_t)-3LL;
        { int16_t r = a + b; printf("%lld\n", (long long) r); }
        { int16_t r = a - b; printf("%lld\n", (long long) r); }
        { int16_t r = a * b; printf("%lld\n", (long long) r); }
        { int16_t r = a & b; printf("%lld\n", (long long) r); }
        { int16_t r = a | b; printf("%lld\n", (long long) r); }
        { int16_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int16_t r = a / b; printf("%lld\n", (long long) r); }
        { int16_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int16_t r = (int16_t)(~a); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    {
        int16_t a = (int16_t)16386LL; int16_t b = (int16_t)9LL;
        { int16_t r = a + b; printf("%lld\n", (long long) r); }
        { int16_t r = a - b; printf("%lld\n", (long long) r); }
        { int16_t r = a * b; printf("%lld\n", (long long) r); }
        { int16_t r = a & b; printf("%lld\n", (long long) r); }
        { int16_t r = a | b; printf("%lld\n", (long long) r); }
        { int16_t r = a ^ b; printf("%lld\n", (long long) r); }
        { int16_t r = a / b; printf("%lld\n", (long long) r); }
        { int16_t r = a % b; printf("%lld\n", (long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { int16_t r = (int16_t)(a << 1); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 1); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a << 3); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 3); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a << 15); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(a >> 15); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(~a); printf("%lld\n", (long long) r); }
        { int16_t r = (int16_t)(0 - a); printf("%lld\n", (long long) r); }
    }
    return 0;
}
