/* GENERATED by scripts/gen_ops_diff.py: reference for ops_u32.mvs */
#include <stdio.h>
#include <stdint.h>

int main(void) {
    {
        uint32_t a = (uint32_t)4294967295LL; uint32_t b = (uint32_t)1LL;
        { uint32_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint32_t r = (uint32_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a << 31); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 31); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint32_t a = (uint32_t)0LL; uint32_t b = (uint32_t)5LL;
        { uint32_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint32_t r = (uint32_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a << 31); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 31); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint32_t a = (uint32_t)4294967295LL; uint32_t b = (uint32_t)3LL;
        { uint32_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint32_t r = (uint32_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a << 31); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 31); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint32_t a = (uint32_t)2147483650LL; uint32_t b = (uint32_t)9LL;
        { uint32_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint32_t r = (uint32_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a << 31); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 31); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint32_t a = (uint32_t)7LL; uint32_t b = (uint32_t)3LL;
        { uint32_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint32_t r = (uint32_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a << 31); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 31); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    {
        uint32_t a = (uint32_t)200LL; uint32_t b = (uint32_t)7LL;
        { uint32_t r = a + b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a - b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a * b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a & b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a | b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a ^ b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a / b; printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = a % b; printf("%llu\n", (unsigned long long) r); }
        printf("%d\n", (int)(a < b));
        printf("%d\n", (int)(a <= b));
        printf("%d\n", (int)(a > b));
        printf("%d\n", (int)(a >= b));
        printf("%d\n", (int)(a == b));
        printf("%d\n", (int)(a != b));
        { uint32_t r = (uint32_t)(a << 1); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 1); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a << 3); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 3); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a << 31); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(a >> 31); printf("%llu\n", (unsigned long long) r); }
        { uint32_t r = (uint32_t)(~a); printf("%llu\n", (unsigned long long) r); }
    }
    return 0;
}
