#!/usr/bin/env python3
"""The std/core API axis of the audit: every exported function must be exercised.

A module that stops compiling, or a function that quietly rots after a language
change, is only caught if something calls it. This enumerates every function
declared in std/ and core/ and checks that the test suite or the examples call
it. Exit code 1 (and a list) when something is uncovered.

Run from the repo root: python3 scripts/api_coverage.py
"""
import os, re, sys

ROOTS = ["std", "core"]
USERS = ["tests", "examples"]

# Functions that cannot be called from a portable test, with the reason. They
# are still type-checked and code-generated by the compile-only coverage below.
EXEMPT = {
    # networking needs a peer and a free port; covered by examples/07_net_*
    "net": "needs a live peer",
    # halting, disabling interrupts or parking the CPU cannot run under a test
    "arch.halt": "stops the machine",
    "arch.wait_event": "blocks until an interrupt",
    "arch.interrupts_off": "privileged",
    "arch.interrupts_on": "privileged",
    "arch.park": "never returns",
    "process.run": "spawns a shell",
    # a server loop that never returns, and a client round trip that needs a
    # peer already serving; examples/12_http covers the rest of std/http
    "http.serve": "serves until the process is stopped",
    "http.fetch": "needs a peer that is already serving",
    "http.log_line": "writes the access log; examples/12_http turns it on",
    "thread.exit": "kills the caller",
    "test.fail": "fails the run by design",
    # the runner's generated main calls these; no test file names them
    "test.begin": "called by the generated test main",
    "test.prefix": "called by the generated test main",
}

def declared():
    """{module: {name: is_method}} for every function declared in std/ and core/."""
    out = {}
    for root in ROOTS:
        for fn in sorted(os.listdir(root)):
            if not fn.endswith(".mvs"):
                continue
            mod = fn[:-4]
            names = out.setdefault(mod, {})
            depth = 0
            for line in open(os.path.join(root, fn), encoding="utf-8"):
                s = line.strip()
                m = re.match(r"(?:export\s+)?func\s+([A-Za-z_][A-Za-z0-9_]*)", s)
                if m:
                    # a method sits inside an impl block (indented), a free
                    # function starts at column 0
                    names[m.group(1)] = line.startswith(" ") or line.startswith("\t")
                if s.startswith("impl "):
                    depth += 1
    return out

def used_text():
    body = []
    for root in USERS:
        for dirpath, _, files in os.walk(root):
            for f in files:
                if f.endswith(".mvs"):
                    body.append(open(os.path.join(dirpath, f), encoding="utf-8").read())
    return "\n".join(body)

def main():
    decl = declared()
    text = used_text()
    missing = []
    total = 0
    for mod, names in sorted(decl.items()):
        for name, is_method in sorted(names.items()):
            if name.startswith("_"):
                continue
            total += 1
            if mod in EXEMPT or "%s.%s" % (mod, name) in EXEMPT:
                continue
            # a free function is called as mod.name( or bare name( after an
            # import; a method as .name(
            pats = [r"\b%s\s*\.\s*%s\s*\(" % (mod, name), r"\.\s*%s\s*\(" % name,
                    r"\b%s\s*\(" % name, r"::\s*%s\s*\(" % name]
            if not any(re.search(p, text) for p in pats):
                missing.append("%s.%s" % (mod, name))
    print("declared: %d function(s) across %d module(s)" % (total, len(decl)))
    if missing:
        print("UNCOVERED: %d" % len(missing))
        for m in missing:
            print("  - " + m)
        return 1
    print("API COVERAGE OK: every std and core function is called by a test or an example")
    return 0

sys.exit(main())
