#!/usr/bin/env python3
"""Generate the operator axis of the audit: tests/diff/ops_<type>.{mvs,c}

Every integer type carried through every arithmetic, bitwise, shift and
comparison operator, with C as the oracle. The pair lands in tests/diff/, so
scripts/difftest.sh (and therefore audit.sh and CI) picks it up with no extra
plumbing: a mismatch means MVS generated wrong code, not that a golden drifted.

Run from the repo root: python3 scripts/gen_ops_diff.py
"""
import os

TYPES = [
    # name, C type, signed, bits
    ("i8",    "int8_t",   True,  8),
    ("i16",   "int16_t",  True,  16),
    ("i32",   "int32_t",  True,  32),
    ("i64",   "int64_t",  True,  64),
    ("isize", "intptr_t", True,  64),
    ("u8",    "uint8_t",  False, 8),
    ("u16",   "uint16_t", False, 16),
    ("u32",   "uint32_t", False, 32),
    ("u64",   "uint64_t", False, 64),
    ("usize", "uintptr_t", False, 64),
]

def pairs(signed, bits):
    """Operand pairs worth testing: edges, wrap points, mixed signs."""
    if signed:
        hi = (1 << (bits - 1)) - 1
        lo = -(1 << (bits - 1))
        return [(hi, 1), (lo, 1), (hi, 3), (lo, 7), (0, 5), (-1, -1),
                (7, 3), (-7, 3), (7, -3), (-7, -3), (hi // 2 + 3, 9)]
    hi = (1 << bits) - 1
    return [(hi, 1), (0, 5), (hi, 3), (hi // 2 + 3, 9), (7, 3), (200 % (hi + 1), 7)]

# (label, MVS expression, C expression). Kept identical on purpose.
BIN = [
    ("add", "a + b"), ("sub", "a - b"), ("mul", "a * b"),
    ("and", "a & b"), ("or", "a | b"), ("xor", "a ^ b"),
]
DIV = [("div", "a / b"), ("rem", "a % b")]
CMP = [("lt", "a < b"), ("le", "a <= b"), ("gt", "a > b"),
       ("ge", "a >= b"), ("eq", "a == b"), ("ne", "a != b")]

def lit(v, name, signed):
    """MVS literal for v. Negative values are written as a unary minus."""
    return str(v)

def cint(v):
    """C literal that needs no suffix warning: the 64-bit edges do not fit the
    signed range, so write them the way <stdint.h> does."""
    if v > 0x7fffffffffffffff:
        return '%dULL' % v
    if v < -0x7fffffffffffffff:
        return '(-9223372036854775807LL - 1)'
    return '%dLL' % v

def gen(name, ctype, signed, bits):
    fmt = "%lld" if signed else "%llu"
    cast = "(long long)" if signed else "(unsigned long long)"
    m = ['// GENERATED by scripts/gen_ops_diff.py: every operator on ' + name,
         '// The C file next to it is the reference; difftest.sh requires identical output.',
         'import { io } from "std";', '', 'func main() -> i8 {']
    c = ['/* GENERATED by scripts/gen_ops_diff.py: reference for ops_%s.mvs */' % name,
         '#include <stdio.h>', '#include <stdint.h>', '', 'int main(void) {']
    n = 0
    for (a, b) in pairs(signed, bits):
        m.append('    {')
        c.append('    {')
        m.append('        let a: %s = %s;' % (name, lit(a, name, signed)))
        m.append('        let b: %s = %s;' % (name, lit(b, name, signed)))
        c.append('        %s a = (%s)%s; %s b = (%s)%s;'
                 % (ctype, ctype, cint(a), ctype, ctype, cint(b)))
        for label, expr in BIN:
            m.append('        let r_%s: %s = %s; io.out("{}", r_%s);' % (label, name, expr, label))
            c.append('        { %s r = a %s b; printf("%s\\n", %s r); }'
                     % (ctype, expr.split()[1], fmt, cast))
            n += 1
        for label, expr in DIV:
            if b == 0:
                continue
            # the one case C leaves undefined and the hardware traps on
            if signed and a == -(1 << (bits - 1)) and b == -1:
                continue
            m.append('        let r_%s: %s = %s; io.out("{}", r_%s);' % (label, name, expr, label))
            c.append('        { %s r = a %s b; printf("%s\\n", %s r); }'
                     % (ctype, expr.split()[1], fmt, cast))
            n += 1
        for label, expr in CMP:
            m.append('        let r_%s: bool = %s; io.out("{}", r_%s as i32);' % (label, expr, label))
            c.append('        printf("%%d\\n", (int)(a %s b));' % expr.split()[1])
            n += 1
        # shifts: only on a non-negative left operand and a count inside the width,
        # which is the region both languages define
        if a >= 0:
            for sh in (1, 3, bits - 1):
                m.append('        let r_shl%d: %s = a << %d; io.out("{}", r_shl%d);' % (sh, name, sh, sh))
                c.append('        { %s r = (%s)(a << %d); printf("%s\\n", %s r); }' % (ctype, ctype, sh, fmt, cast))
                m.append('        let r_shr%d: %s = a >> %d; io.out("{}", r_shr%d);' % (sh, name, sh, sh))
                c.append('        { %s r = (%s)(a >> %d); printf("%s\\n", %s r); }' % (ctype, ctype, sh, fmt, cast))
                n += 2
        # unary
        m.append('        let r_not: %s = ~a; io.out("{}", r_not);' % name)
        c.append('        { %s r = (%s)(~a); printf("%s\\n", %s r); }' % (ctype, ctype, fmt, cast))
        n += 1
        if signed:
            m.append('        let r_neg: %s = 0 - a; io.out("{}", r_neg);' % name)
            c.append('        { %s r = (%s)(0 - a); printf("%s\\n", %s r); }' % (ctype, ctype, fmt, cast))
            n += 1
        m.append('    }')
        c.append('    }')
    m += ['    return 0;', '}', '']
    c += ['    return 0;', '}', '']
    return '\n'.join(m), '\n'.join(c), n

total = 0
os.makedirs('tests/diff', exist_ok=True)
for name, ctype, signed, bits in TYPES:
    mvs, cref, n = gen(name, ctype, signed, bits)
    open('tests/diff/ops_%s.mvs' % name, 'w', newline='\n').write(mvs)
    open('tests/diff/ops_%s.c' % name, 'w', newline='\n').write(cref)
    total += n
    print('ops_%s: %d checks' % (name, n))
print('total %d operator checks across %d types' % (total, len(TYPES)))
