#!/bin/sh
# Systematic feature-matrix audit.
#
# Hand-picked probing finds a couple of bugs per session and never converges,
# because it samples the surface instead of enumerating it. This script
# enumerates: for EVERY type it generates a program that carries a value of
# that type through EVERY context the language offers, and every generated
# program CHECKS ITSELF, returning a distinct exit code that names the context
# that broke. No golden files: the programs are their own oracle.
#
#   type    x   context
#   i8..i128, u8..u128, f32, f64, bool, char, str, pointer, struct, enum
#   local, global, parameter, return value, struct field, array element,
#   Vec element, Option payload, enum payload, match binding, method receiver,
#   generic instance, io.out argument
#
# Usage: sh scripts/matrix.sh [elf64|arm64|win64]   (from the repo root)
set -u
MVS=${MVS:-./mvs}
MODE=${1:-elf64}
case "$MODE" in
    arm64) TARGET="--target arm64"; CC=${CROSS:-aarch64-linux-gnu-gcc}; LINK="-static -lm -lpthread"; RUN=${QEMU:-qemu-aarch64} ;;
    win64) TARGET=""; CC=""; LINK=""; RUN="" ;;
    *)     TARGET="--target elf64"; CC=${CC:-gcc}; LINK="-no-pie -lm -lpthread"; RUN="" ;;
esac
TMP=$(mktemp -d)
fail=0
pass=0

# $1 = type name, $2 = a literal of that type, $3 = a second literal,
# $4 = the sum of the two as it must print, $5 = "int" or "float" or "other"
emit() {
    ty=$1; a=$2; b=$3; want=$4; kind=$5
    f=$TMP/m_$ty.mvs
    cat > "$f" <<EOF
// generated by scripts/matrix.sh: carry a $ty through every context
import { io } from "std";
import { Vec } from "std/vec";
import { Option, Some, None } from "std/option";

struct Holder { field: $ty; tag: i64; }
struct GBox<T> { v: T; }
enum Carry { One($ty), None2 }

let global_v: $ty = $a;

func by_param(x: $ty) -> $ty { return x; }
func by_return() -> $ty { return $a; }

impl Holder {
    func get(self: *Holder) -> $ty { return self.field; }
}

func main() -> i8 {
    let local: $ty = $a;
    if (!same(local, $a)) { return 1; }
    if (!same(global_v, $a)) { return 2; }
    if (!same(by_param($a), $a)) { return 3; }
    if (!same(by_return(), $a)) { return 4; }

    let h: Holder = Holder { field: $b, tag: 7 };
    if (!same(h.field, $b)) { return 5; }
    if (!same(h.get(), $b)) { return 6; }

    let arr: [$ty; 3] = [$a, $b, $a];
    let idx: i64 = 1;
    if (!same(arr[idx], $b)) { return 7; }
    arr[idx] = $a;
    if (!same(arr[idx], $a)) { return 8; }

    let v: Vec<$ty> = Vec<$ty>::new();
    v.push($a);
    v.push($b);
    if (!same(v.get(1), $b)) { return 9; }
    v.drop();

    let o: Option<$ty> = Some($b);
    if (!same(o.unwrap(), $b)) { return 10; }
    match (o) {
        Some(x) => { if (!same(x, $b)) { return 11; } }
        None => { return 12; }
    }

    let c: Carry = Carry::One($a);
    match (c) {
        Carry::One(x) => { if (!same(x, $a)) { return 13; } }
        Carry::None2 => { return 14; }
    }

    let g: GBox<$ty> = GBox<$ty> { v: $b };
    if (!same(g.v, $b)) { return 15; }

    io.out("{} {} {}", local, h.field, sum($a, $b));
    return 0;
}

func same(x: $ty, y: $ty) -> bool { return x == y; }
EOF
    if [ "$kind" = "other" ]; then
        echo "func sum(x: $ty, y: $ty) -> $ty { return y; }" >> "$f"
    else
        echo "func sum(x: $ty, y: $ty) -> $ty { return x + y; }" >> "$f"
    fi

    base=${f%.mvs}
    if ! "$MVS" "$f" $TARGET > "$TMP/build.txt" 2>&1; then
        echo "FAIL  $ty (compile)"; head -3 "$TMP/build.txt"; fail=$((fail+1)); return
    fi
    if [ "$MODE" = "win64" ]; then
        exe="$base.exe"
    else
        exe=$TMP/run_$ty
        if ! $CC "$base.o" -o "$exe" $LINK 2>"$TMP/link.txt"; then
            echo "FAIL  $ty (link)"; head -3 "$TMP/link.txt"; fail=$((fail+1)); return
        fi
    fi
    out=$($RUN "$exe" 2>&1)
    rc=$?
    rm -f "$base.o" "$base.asm" "$base.s" "$base.obj" "$base.exe"
    if [ $rc -ne 0 ]; then
        echo "FAIL  $ty (self-check $rc failed: see the return codes in the generator)"
        fail=$((fail+1)); return
    fi
    if [ "$out" != "$want" ]; then
        echo "FAIL  $ty (printed '$out', expected '$want')"; fail=$((fail+1)); return
    fi
    pass=$((pass+1)); echo "ok    $ty"
}

echo "=== feature matrix on $MODE: every type through every context ==="
emit i8    "1"    "2"    "1 2 3"                   int
emit i16   "100"  "200"  "100 200 300"             int
emit i32   "1000" "2000" "1000 2000 3000"          int
emit i64   "5"    "7"    "5 7 12"                   int
emit isize "5"    "7"    "5 7 12"                   int
emit u8    "10"   "20"   "10 20 30"                 int
emit u16   "300"  "400"  "300 400 700"              int
emit u32   "5000" "6000" "5000 6000 11000"          int
emit u64   "9"    "11"   "9 11 20"                  int
emit usize "9"    "11"   "9 11 20"                  int
emit f32   "1.5"  "2.5"  "1.500000 2.500000 4.000000" float
emit f64   "1.25" "2.75" "1.250000 2.750000 4.000000" float
emit bool  "true" "false" "1 0 0"                   other
emit char  "'A'"  "'B'"  "A B B"                    other
emit str   "\"aa\"" "\"bb\"" "aa bb bb"             other

echo
if [ "$fail" -gt 0 ]; then echo "MATRIX FAILED: $fail type(s) broke, $pass passed"; rm -rf "$TMP"; exit 1; fi
echo "MATRIX OK: $pass type(s) carried through every context"
rm -rf "$TMP"
